# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.89.0"

default_platform :ios

project_file = 'Phone Status Glance.xcodeproj'

platform :ios do
  before_all do
    cocoapods
  end

  def commit_bump (project_file)
    commit_version_bump(xcodeproj: project_file, message: "Bump build number")
  end

  def bump_build (project_file)
    increment_build_number(xcodeproj: project_file)
    commit_bump(project_file)
  end

  def bump_version (project_file, type)
    increment_version_number(xcodeproj: project_file, bump_type: type)
    commit_bump(project_file)
  end

  def tag_with_version(message)
    version = get_info_plist_value(path: 'Phone Stats/Info.plist', key: 'CFBundleShortVersionString')
    build = get_info_plist_value(path: 'Phone Stats/Info.plist', key: 'CFBundleVersion')
    add_git_tag(
      tag: message + "-" + version + "-" + build
    )
  end

  lane :getmatch do
    match(app_identifier: "io.telliott.Phone-Stats", readonly: true)
    match(app_identifier: "io.telliott.Phone-Stats.watchkitapp", readonly: true)
    match(app_identifier: "io.telliott.Phone-Stats.watchkitapp.watchkitextension", readonly: true)
    match(app_identifier: "io.telliott.GroupFileViewer", readonly: true)
  end

  desc "Increment patch version number"
  lane :bump_patch do
    bump_version(project_file, "patch")
  end

  desc "Increment major version number"
  lane :bump_major do
    bump_version(project_file, "major")
  end

  desc "Increment minor version number"
  lane :bump_minor do
    bump_version(project_file, "minor")
  end

  desc "Runs all the tests"
  lane :test do
    snapshot()
    frameit
  end

  desc "Submit a new Beta Build without Screenshots"
  lane :betafast do
    bump_build(project_file)
    gym(scheme: "Phone Status Glance")
    pilot(skip_waiting_for_build_processing: true)
    tag_with_version("betafast")
  end

  lane :justgym do
    gym(scheme: "Phone Status Glance", use_legacy_build_api: true) # Build your app - more options available
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    bump_build(project_file)
    snapshot()
    gym(scheme: "Phone Status Glance", use_legacy_build_api: true) # Build your app - more options available
    pilot
    tag_with_version("beta")
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    bump_build(project_file)
    snapshot()
    gym(scheme: "Phone Status Glance", use_legacy_build_api: true) # Build your app - more options available
    deliver(force: true)
    tag_with_version("deliver")
  end
end
